### ISSUE TITLE
lambda.zip package folder missing for copy-zips

### ISSUE THREAD

**Issue by mufaddalq** [aws-quickstart/quickstart-aws-acm-certificate#13]
On ln 116, we expect functions/packages/lambda.zip to be available in copy-zips submodule. This is missing and only contains functions/source. As a result the lambda copy fails.

**Comment by gargana** [comment]
Lambda .zip packages are not present in /functions/packages/. If you deploy your templates without Lambda .zip packages, you'll hit the CopyZips error.

The latest version of [taskcat](https://github.com/aws-quickstart/taskcat) packages Lambda functions (into .zip files) for you, but note that it requires access to a docker daemon to do that. Once taskcat builds all the Lambda packages, it will upload them to S3 along with your templates, and you shouldn't hit the CopyZips issue. If you run taskcat package against this Quick Start module you should not have this issue.

Alternatively the packaged artifacts can be fetched from s3:
aws s3 cp --recursive s3://aws-quickstart/quickstart-aws-acm-certificate/ ./quickstart-aws-acm-certificate/

**Comment by gargana** [comment]
For the taskcat route
```
# build the lambda zip files
taskcat package
# upload to S3
taskcat upload
```

**Comment by gargana** [comment]
I found that the problem was the project I tested with already contained the Copy-Zips project and Lambda zip. I have resolved this bug with this commit. https://github.com/aws-quickstart/quickstart-aws-acm-certificate/commit/66061df67c9ea49db512a14eac6077c668e90b8e
